export const BOOK_CATEGORY_ARRAY = [
  'Adventure',
  'Biography',
  'Classic',
  'Drama',
  'Dystopian',
  'Fantasy',
  'Fiction',
  'Historical Fiction',
  'Historical',
  'Horror',
  'Humor',
  'Mystery',
  'Non-fiction',
  'Poetry',
  'Psychological Suspense',
  'Romance',
  'Science Fiction',
  'Thriller',
];
